[package]
name = "redis-ac"
version = "0.1.0"
authors = ["Yushi Omote <yushi.omote@sbibits.com>"]
edition = "2018"

[features]
default = []
geospatial = ["redis/geospatial"]

[dependencies]
futures = "0.1"
redis = "0.13"

[dev-dependencies]
tokio = "0.1"