name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
        - 6379:6379
        options: --entrypoint redis-server

    env:
      NO_REDIS: 1
      RUST_TEST_THREADS: 1
      SAMPLE_COUNT: 10

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Build (geospatial)
      run: cargo build --verbose --features geospatial
    - name: Run tests (with items)
      run: cargo test --verbose
      env:
        SAMPLE_COUNT: 10000
    - name: Run tests (without items)
      run: cargo test --verbose
      env:
        SAMPLE_COUNT: 0
    - name: Install nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Test nightly (with readme)
      run: cargo test --verbose --features readme
    - name: Test for coverage
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --no-fail-fast
      env:
        CARGO_INCREMENTAL: 0
        RUSTFLAGS: -Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads
    - name: Get coverage
      uses: actions-rs/grcov@v0.1
    - name: Coveralls upload
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ${{ steps.coverage.outputs.report }}
